version: "3.3"

services:
  django-backend:
    restart: always
    build:
      context: ./django-backend # django service folder
    image: djangobackend

  postgresql-db:
    restart: always
    image: postgres
    env_file: ./postgresql-db/.pg-env

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "8000:80"
