# Generated by Django 5.0.4 on 2024-04-09 17:38

import django.db.models.deletion
from django.db import migrations, models




class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_name_category_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productDescription', models.TextField()),
                ('is_employ', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product.models.content_file_name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
