# Generated by Django 5.0.4 on 2024-04-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productDescription',
            field=models.TextField(max_length=190),
        ),
    ]
