# Generated by Django 5.0.4 on 2024-04-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_productdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_employ',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
